name: Trigger auto deployment for action-now-api-one

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '/src/ActionNow.Api.One/Docker/**'
    - '.github/workflows/action-now-api-one-AutoDeployTrigger-b3f709ef-27a3-4e22-95d6-79974158b271.yml'

  # Allow manual trigger 
  workflow_dispatch:
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.ACTIONNOWAPIONE_AZURE_CREDENTIALS }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}/src/ActionNow.Api.One/Docker 
          registryUrl: sprintdeploylearnrepeatregistry.azurecr.io
          registryUsername: ${{ secrets.ACTIONNOWAPIONE_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.ACTIONNOWAPIONE_REGISTRY_PASSWORD }}
          containerAppName: action-now-api-one
          resourceGroup: action-now-rg
          imageToBuild: sprintdeploylearnrepeatregistry.azurecr.io/action-now-api-one:${{ github.sha }}
          
            

     

